Repository cyclus/cyclus.github.com, pull requests merged in 2024-03, with the labels that each got.

#340 Third-party archetype list update
  source/user/index.rst
Labels: 3 - Done

#341 change instances of master branch to main
  README.rst
  gh-project.mk
  rever.xsh
  source/kernel/build_from_source.rst
  source/kernel/contributing_to_cyclus.rst
  source/kernel/style_guide.rst
  source/numpydoc/numpydoc.py
  source/user/tutorial/run_cyclus_native.rst
Labels: 0 - Backlog, 2 - Working

#343 Remove weekly meeting information
  source/index.rst
Labels: 1 - Ready

#342 Update list of contributors
  source/index.rst
Labels: 1 - Ready
